spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

jwt:
  header: Authorization
  prefix: Bearer
  secret-key: ce032ca2ca8daf17719a7cb37e27a6b02a815f3730a9b06fe859e288a1e826c85d3f90981d6be0b063fec2257985ee4e6031508be22a59799f8209d40129d4fc
  access-token:
    expiration-time: 7200000 # 2시간 (밀리초)
  refresh-token:
    expiration-time: 2592000000 # 30일 (밀리초)