micronaut:
  application:
    name: agent-server
  server:
    port: 3930
  profiles:
    active: local

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/test
    username: user
    password: pass
    driverClassName: org.postgresql.Driver

app:
  agent:
    secret: default-secret

logger:
  levels:
    ROOT: INFO
    com.pandaterry.infrastructure.filters: DEBUG
    reactor.util.context: DEBUG