spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

server:
  port: 8080

jwt:
  secret-key: ${JWT_SECRET_KEY:your-secret-key-here}
  access-token:
    expiration-time: 7200000 # 2시간 (밀리초)
  refresh-token:
    expiration-time: 2592000000 # 30일 (밀리초)
