spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: nl-sql-service
          uri: http://localhost:8082
          predicates:
            - Path=/sql/**

        - id: rate-limit-service
          uri: http://localhost:8083
          predicates:
            - Path=/usage/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics

server:
  port: 8080

jwt:
  secret: 01234567890123456789012345678901
  header: Authorization
  prefix: Bearer