server:
  port: 8080
#  servlet:
#    context-path: /api

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  profiles:
    active: local

jwt:
  secret: 01234567890123456789012345678901
  header: Authorization
  prefix: Bearer
